project:
  type: website

website:
  title: "IS415-GAA-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Project"
        href: "project/project.html"
      - text: "Poster"
        href: "poster/poster.html"
      - text: "User Guide"
        href: "user_guide/user_guide.html"
      - text: "Minutes of Meeting"
        href: "meeting/meeting.html"
    
      
format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

