project:
  type: website

website:
  title: "IS415-GAA-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Project"
        href: "project/project.html"
      
      
format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

