project:
  type: website

website:
  title: "IS415-GAA-Project"
  navbar:
    left:
     - text: "Proposal"
      menu:
        href: "proposal/project_proposal.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

